//Example 6-5 Power Generation and Wind Loading of Wind Turbine
D = 9 //diameter of wind turbine blade [m]
V_1 = 11 //minimum speed for power generation [m/s]
Wdot_act = 0.4 //Actual power generated by turbine [kW]
beta1 = 1 //momentum flux correction factor
rho = 1.22 //density of air [kg/m^3]